apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrapp
spec:
  selector:
    matchLabels:
      app: qrapp
  replicas: 2
  template:
    metadata:
      labels:
        app: qrapp
    spec:
      containers:
        - name: qrapp
          image: therealsojay/qrcodeapp:1.0.60
          # ports:
          #   - containerPort: 5001
