name: Update Deployment Image

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest image tag from Docker registry
        id: fetch_tag
        run: |
          LATEST_TAG=$(curl -s https://hub.docker.com/v2/repositories/therealsojay/qrcodeapp/tags/latest | jq -r '.name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Update image tag in deployment.yaml
        run: |
          NEW_IMAGE="therealsojay/qrcodeapp:${{ env.LATEST_TAG }}"
          yq eval ".spec.template.spec.containers[0].image = \"${NEW_IMAGE}\"" -i manifests/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add manifests/deployment.yaml
          git commit -m "Update image tag to ${{ env.LATEST_TAG }}"
          git push origin main
