name: Update Deployment Image

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  update-deployment:
    name: Update Kubernetes Deployment YAML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (required for `yq`)
        uses: actions/setup-node@v4
        with:
          node-version: 20.8.1

      - name: Install yq (YAML processor)
        run: |
          sudo npm install -g yq

      # Explicitly set the IMAGE_TAG to the latest tag you want to use.
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Get current image tag
        id: get_current_tag
        run: |
          CURRENT_TAG=$(yq eval '.spec.template.spec.containers[0].image' manifests/deployment.yaml | cut -d':' -f2)
          echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV

      - name: Check if image tag needs to be updated
        id: check_tag
        run: |
          if [ "${{ env.CURRENT_TAG }}" == "${{ env.IMAGE_TAG }}" ]; then
            echo "Image tag is already up to date."
            echo "update_needed=false" >> $GITHUB_ENV
          else
            echo "Image tag needs to be updated."
            echo "update_needed=true" >> $GITHUB_ENV
          fi

      - name: Update image tag in deployment.yaml
        if: env.update_needed == 'true'
        run: |
          NEW_IMAGE="therealsojay/qrcodeapp:${{ env.IMAGE_TAG }}"
          yq eval ".spec.template.spec.containers[0].image = \"${NEW_IMAGE}\"" -i manifests/deployment.yaml

      - name: Commit and push changes
        if: env.update_needed == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add manifests/deployment.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push origin main
